"""Repository ports.

The engine never imports SQLAlchemy. It depends on these Protocols; the
``database`` package supplies the adapters, and the tests supply in-memory
fakes. This is what keeps the domain layer testable without a database
(DECISIONS D-004).
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from engine.core.models import (
    Character,
    CharacterKnowledge,
    CharacterSkill,
    Event,
    Fact,
    Faction,
    GameSession,
    InventoryItem,
    Item,
    Location,
    Memory,
    NarrativeSegment,
    PlotThread,
    Quest,
    Relationship,
    RelationshipChange,
    Skill,
    World,
)
from engine.core.mutations import ChangeSet


@runtime_checkable
class WorldRepository(Protocol):
    async def get(self, world_id: str) -> World | None: ...
    async def save(self, world: World) -> None: ...
    async def list_all(self) -> list[World]: ...


@runtime_checkable
class LocationRepository(Protocol):
    async def get(self, location_id: str) -> Location | None: ...
    async def get_by_key(self, world_id: str, key: str) -> Location | None: ...
    async def list_for_world(self, world_id: str) -> list[Location]: ...
    async def children(self, location_id: str) -> list[Location]: ...


@runtime_checkable
class FactionRepository(Protocol):
    async def get(self, faction_id: str) -> Faction | None: ...
    async def get_by_key(self, world_id: str, key: str) -> Faction | None: ...
    async def list_for_world(self, world_id: str) -> list[Faction]: ...


@runtime_checkable
class CharacterRepository(Protocol):
    async def get(self, character_id: str) -> Character | None: ...
    async def get_by_key(self, world_id: str, key: str) -> Character | None: ...
    async def list_for_world(self, world_id: str, *, alive_only: bool = True) -> list[Character]: ...
    async def list_at_location(
        self, world_id: str, location_id: str, *, alive_only: bool = True
    ) -> list[Character]: ...
    async def list_by_type(self, world_id: str, character_type: str) -> list[Character]: ...


@runtime_checkable
class RelationshipRepository(Protocol):
    async def get(self, character_a_id: str, character_b_id: str) -> Relationship | None: ...
    async def list_for_character(self, character_id: str) -> list[Relationship]: ...
    async def list_changes(self, character_id: str, limit: int = 50) -> list[RelationshipChange]: ...


@runtime_checkable
class KnowledgeRepository(Protocol):
    async def get_fact(self, fact_id: str) -> Fact | None: ...
    async def get_fact_by_key(self, world_id: str, key: str) -> Fact | None: ...
    async def list_facts(self, world_id: str) -> list[Fact]: ...
    async def get_knowledge(self, character_id: str, fact_id: str) -> CharacterKnowledge | None: ...
    async def list_known(self, character_id: str) -> list[tuple[CharacterKnowledge, Fact]]:
        """Only rows whose state is not UNKNOWN. This is the god-view firewall."""
        ...

    async def list_knowers(self, fact_id: str) -> list[CharacterKnowledge]: ...


@runtime_checkable
class MemoryRepository(Protocol):
    async def list_for_owner(
        self, owner_character_id: str, *, memory_types: list[str] | None = None, limit: int = 200
    ) -> list[Memory]: ...
    async def add(self, memory: Memory) -> None: ...
    async def touch(self, memory_id: str, at_minute: int) -> None: ...


@runtime_checkable
class ItemRepository(Protocol):
    async def get_by_key(self, world_id: str, key: str) -> Item | None: ...
    async def list_for_world(self, world_id: str) -> list[Item]: ...
    async def list_inventory(self, character_id: str) -> list[InventoryItem]: ...
    async def get_inventory_item(self, character_id: str, item_key: str) -> InventoryItem | None: ...


@runtime_checkable
class SkillRepository(Protocol):
    async def get_by_key(self, world_id: str, key: str) -> Skill | None: ...
    async def list_for_world(self, world_id: str) -> list[Skill]: ...
    async def list_for_character(self, character_id: str) -> list[CharacterSkill]: ...
    async def get_for_character(self, character_id: str, skill_key: str) -> CharacterSkill | None: ...


@runtime_checkable
class QuestRepository(Protocol):
    async def get(self, quest_id: str) -> Quest | None: ...
    async def get_by_key(self, world_id: str, key: str) -> Quest | None: ...
    async def list_for_world(self, world_id: str, *, status: str | None = None) -> list[Quest]: ...


@runtime_checkable
class EventRepository(Protocol):
    """Append-only. There is deliberately no update() or delete()."""

    async def append(self, event: Event) -> None: ...
    async def list_recent(self, world_id: str, limit: int = 20) -> list[Event]: ...
    async def list_for_actor(self, actor_id: str, limit: int = 20) -> list[Event]: ...
    async def list_since(self, world_id: str, since_minute: int) -> list[Event]: ...
    async def get(self, event_id: str) -> Event | None: ...


@runtime_checkable
class PlotThreadRepository(Protocol):
    async def get_by_key(self, world_id: str, key: str) -> PlotThread | None: ...
    async def list_for_world(self, world_id: str, *, status: str | None = None) -> list[PlotThread]: ...


@runtime_checkable
class SessionRepository(Protocol):
    async def get(self, session_id: str) -> GameSession | None: ...
    async def save(self, session: GameSession) -> None: ...
    async def list_for_world(self, world_id: str) -> list[GameSession]: ...


@runtime_checkable
class TurnRepository(Protocol):
    async def record(self, turn: dict[str, Any]) -> None: ...
    async def get(self, turn_id: str) -> dict[str, Any] | None: ...
    async def get_by_idempotency_key(self, key: str) -> dict[str, Any] | None: ...
    async def list_for_session(self, session_id: str, limit: int = 50) -> list[dict[str, Any]]: ...
    async def append_narrative(self, segment: NarrativeSegment) -> None: ...
    async def list_narrative(self, session_id: str, limit: int = 10) -> list[NarrativeSegment]: ...
    async def save_trace(self, trace: dict[str, Any]) -> None: ...
    async def get_trace(self, turn_id: str) -> dict[str, Any] | None: ...


@runtime_checkable
class UnitOfWork(Protocol):
    """Transaction boundary for one turn (Prompt section 58).

    The repositories are declared as read-only properties rather than plain
    attributes so that an adapter may expose a concrete subtype of each port -
    mutable protocol attributes are invariant, properties are covariant.
    """

    @property
    def worlds(self) -> WorldRepository: ...
    @property
    def locations(self) -> LocationRepository: ...
    @property
    def factions(self) -> FactionRepository: ...
    @property
    def characters(self) -> CharacterRepository: ...
    @property
    def relationships(self) -> RelationshipRepository: ...
    @property
    def knowledge(self) -> KnowledgeRepository: ...
    @property
    def memories(self) -> MemoryRepository: ...
    @property
    def items(self) -> ItemRepository: ...
    @property
    def skills(self) -> SkillRepository: ...
    @property
    def quests(self) -> QuestRepository: ...
    @property
    def events(self) -> EventRepository: ...
    @property
    def plot_threads(self) -> PlotThreadRepository: ...
    @property
    def sessions(self) -> SessionRepository: ...
    @property
    def turns(self) -> TurnRepository: ...

    async def __aenter__(self) -> UnitOfWork: ...
    async def __aexit__(self, *exc: Any) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def apply(self, change_set: ChangeSet) -> None:
        """Apply a validated ChangeSet. Must be all-or-nothing."""
        ...
