"""platform tenancy and content releases

Revision ID: 2854c8807876
Revises: e4b9a07c3d15
Create Date: 2026-08-13 01:01:44.951556
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - autogenerate renders JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql

revision: str = '2854c8807876'
down_revision: Union[str, None] = 'e4b9a07c3d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('delete_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_quota_monthly', sa.Integer(), nullable=False),
    sa.Column('user_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('email_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_email_tokens_user_purpose', ['user_id', 'purpose', 'used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('llm_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider_key')
    )
    with op.batch_alter_table('llm_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('project_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'slug', name='uq_project_owner_slug')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('playthrough_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_microunits', sa.BigInteger(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_ledger_playthrough_id'), ['playthrough_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_project_id'), ['project_id'], unique=False)

    op.create_table('project_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('document', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('diagnostics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'revision', name='uq_project_revision')
    )
    with op.batch_alter_table('project_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_revisions_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_revisions_project_id'), ['project_id'], unique=False)

    op.create_table('content_releases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('moderation_status', sa.String(length=32), nullable=False),
    sa.Column('share_token_hash', sa.String(length=64), nullable=True),
    sa.Column('artifact', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['project_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_release_project_version')
    )
    with op.batch_alter_table('content_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_releases_checksum'), ['checksum'], unique=True)
        batch_op.create_index(batch_op.f('ix_content_releases_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_releases_moderation_status'), ['moderation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_releases_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_releases_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_releases_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_releases_revision_id'), ['revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_releases_share_token_hash'), ['share_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_releases_visibility'), ['visibility'], unique=False)

    op.create_table('moderation_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('submitter_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['content_releases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_cases_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_cases_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_moderation_cases_status'), ['status'], unique=False)

    op.create_table('playthroughs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_key', sa.String(length=80), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=True),
    sa.Column('game_session_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('player_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['content_releases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_session_id'),
    sa.UniqueConstraint('world_id')
    )
    with op.batch_alter_table('playthroughs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playthroughs_is_preview'), ['is_preview'], unique=False)
        batch_op.create_index(batch_op.f('ix_playthroughs_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playthroughs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_playthroughs_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('release_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['content_releases.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))
        batch_op.add_column(sa.Column('resources', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))
        batch_op.add_column(sa.Column('progressions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))
        batch_op.add_column(sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playthrough_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_sessions_playthrough_id'), ['playthrough_id'], unique=False)

    with op.batch_alter_table('save_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('playthrough_id', sa.String(length=36), nullable=True))
        batch_op.drop_index(batch_op.f('idx_save_slots_session'))
        batch_op.drop_index(batch_op.f('idx_save_slots_world'))
        batch_op.create_index(batch_op.f('ix_save_slots_playthrough_id'), ['playthrough_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_save_slots_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_save_slots_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_save_slots_world_id'), ['world_id'], unique=False)

    with op.batch_alter_table('worlds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('playthrough_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_worlds_playthrough_id'), ['playthrough_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worlds_release_id'), ['release_id'], unique=False)

    # PostgreSQL provides a second, database-enforced tenant boundary. SQLite
    # development and tests use the same ownership predicates in repositories.
    if op.get_bind().dialect.name == "postgresql":
        tenant_tables = {
            "projects": "owner_id",
            "assets": "owner_id",
            "llm_credentials": "user_id",
            "playthroughs": "user_id",
            "usage_ledger": "user_id",
            "save_slots": "user_id",
        }
        for table, column in tenant_tables.items():
            op.execute(sa.text(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY'))
            op.execute(
                sa.text(
                    f'CREATE POLICY {table}_tenant_policy ON "{table}" '
                    f"USING ({column} = current_setting('app.current_user_id', true)) "
                    f"WITH CHECK ({column} = current_setting('app.current_user_id', true))"
                )
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worlds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worlds_release_id'))
        batch_op.drop_index(batch_op.f('ix_worlds_playthrough_id'))
        batch_op.drop_column('playthrough_id')
        batch_op.drop_column('release_id')

    with op.batch_alter_table('save_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_save_slots_world_id'))
        batch_op.drop_index(batch_op.f('ix_save_slots_user_id'))
        batch_op.drop_index(batch_op.f('ix_save_slots_session_id'))
        batch_op.drop_index(batch_op.f('ix_save_slots_playthrough_id'))
        batch_op.create_index(batch_op.f('idx_save_slots_world'), ['world_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_save_slots_session'), ['session_id'], unique=False)
        batch_op.drop_column('playthrough_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_sessions_playthrough_id'))
        batch_op.drop_column('playthrough_id')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('properties')
        batch_op.drop_column('progressions')
        batch_op.drop_column('resources')
        batch_op.drop_column('attributes')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_reports_release_id'))

    op.drop_table('reports')
    with op.batch_alter_table('playthroughs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playthroughs_user_id'))
        batch_op.drop_index(batch_op.f('ix_playthroughs_status'))
        batch_op.drop_index(batch_op.f('ix_playthroughs_release_id'))
        batch_op.drop_index(batch_op.f('ix_playthroughs_is_preview'))

    op.drop_table('playthroughs')
    with op.batch_alter_table('moderation_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_cases_status'))
        batch_op.drop_index(batch_op.f('ix_moderation_cases_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_moderation_cases_release_id'))

    op.drop_table('moderation_cases')
    with op.batch_alter_table('content_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_releases_visibility'))
        batch_op.drop_index(batch_op.f('ix_content_releases_share_token_hash'))
        batch_op.drop_index(batch_op.f('ix_content_releases_revision_id'))
        batch_op.drop_index(batch_op.f('ix_content_releases_rating'))
        batch_op.drop_index(batch_op.f('ix_content_releases_project_id'))
        batch_op.drop_index(batch_op.f('ix_content_releases_owner_id'))
        batch_op.drop_index(batch_op.f('ix_content_releases_moderation_status'))
        batch_op.drop_index(batch_op.f('ix_content_releases_locale'))
        batch_op.drop_index(batch_op.f('ix_content_releases_checksum'))

    op.drop_table('content_releases')
    with op.batch_alter_table('project_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_revisions_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_revisions_author_id'))

    op.drop_table('project_revisions')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_project_id'))
        batch_op.drop_index(batch_op.f('ix_assets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_assets_checksum'))

    op.drop_table('assets')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role'))

    op.drop_table('user_roles')
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_ledger_playthrough_id'))
        batch_op.drop_index(batch_op.f('ix_usage_ledger_created_at'))

    op.drop_table('usage_ledger')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    with op.batch_alter_table('llm_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_credentials_user_id'))

    op.drop_table('llm_credentials')
    with op.batch_alter_table('email_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_email_tokens_expires_at'))
        batch_op.drop_index('idx_email_tokens_user_purpose')

    op.drop_table('email_tokens')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
