"""initial schema

Revision ID: 52add84b754e
Revises: 
Create Date: 2026-08-09 02:18:59.938915
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - referenced by the rendered JSONB variants
from sqlalchemy.dialects import postgresql

revision: str = '52add84b754e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_knowledge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_state', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_character_id', sa.String(length=36), nullable=True),
    sa.Column('learned_at_minute', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'fact_id', name='uq_knowledge_char_fact')
    )
    with op.batch_alter_table('character_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_knowledge_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_knowledge_fact_id'), ['fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_knowledge_knowledge_state'), ['knowledge_state'], unique=False)

    op.create_table('character_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('skill_key', sa.String(length=120), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('learned_at_minute', sa.BigInteger(), nullable=False),
    sa.Column('last_used_minute', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'skill_key', name='uq_char_skill')
    )
    with op.batch_alter_table('character_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_skills_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_skills_skill_key'), ['skill_key'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('target_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('causes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cause_event_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('world_minute', sa.BigInteger(), nullable=False),
    sa.Column('rng_seed', sa.String(length=64), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('visibility', sa.String(length=40), nullable=False),
    sa.Column('witnesses', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_actor', ['actor_id', 'world_minute'], unique=False)
        batch_op.create_index('idx_events_world_minute', ['world_id', 'world_minute'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_turn_id'), ['turn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_world_id'), ['world_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_world_minute'), ['world_minute'], unique=False)

    op.create_table('facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('truth_value', sa.Boolean(), nullable=True),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('sensitivity', sa.Float(), nullable=False),
    sa.Column('subject_character_key', sa.String(length=120), nullable=True),
    sa.Column('related_characters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at_minute', sa.BigInteger(), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key', name='uq_fact_world_key')
    )
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facts_world_id'), ['world_id'], unique=False)

    op.create_table('game_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('player_character_id', sa.String(length=36), nullable=False),
    sa.Column('session_seed', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_sessions_player_character_id'), ['player_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_sessions_world_id'), ['world_id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('item_key', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.Column('bound', sa.Boolean(), nullable=False),
    sa.Column('acquired_at_minute', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'item_key', name='uq_inventory_char_item')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_item_key'), ['item_key'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=60), nullable=False),
    sa.Column('rarity', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effects', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('item_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key', name='uq_item_world_key')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_world_id'), ['world_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('owner_character_id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=40), nullable=False),
    sa.Column('memory_tag', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('emotional_valence', sa.Float(), nullable=False),
    sa.Column('related_characters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('related_event_id', sa.String(length=36), nullable=True),
    sa.Column('related_location_id', sa.String(length=36), nullable=True),
    sa.Column('created_at_minute', sa.BigInteger(), nullable=False),
    sa.Column('last_recalled_minute', sa.BigInteger(), nullable=False),
    sa.Column('recall_count', sa.Integer(), nullable=False),
    sa.Column('decay', sa.Float(), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index('idx_memories_owner_importance', ['owner_character_id', 'importance'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_memory_type'), ['memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_owner_character_id'), ['owner_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_world_id'), ['world_id'], unique=False)

    op.create_table('narrative_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('world_minute', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('narrative_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_narrative_segments_session_id'), ['session_id'], unique=False)

    op.create_table('plot_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('participants', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('unresolved_questions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('foreshadowing', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('related_facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('last_advanced_minute', sa.BigInteger(), nullable=False),
    sa.Column('next_beat_hint', sa.Text(), nullable=False),
    sa.Column('escalation_pressure', sa.Float(), nullable=False),
    sa.Column('thread_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key', name='uq_thread_world_key')
    )
    with op.batch_alter_table('plot_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_threads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_plot_threads_world_id'), ['world_id'], unique=False)

    op.create_table('quests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('giver_character_key', sa.String(length=120), nullable=True),
    sa.Column('assignee_character_key', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('goal', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('constraints', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('participants', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('rewards', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('failure_conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at_minute', sa.BigInteger(), nullable=True),
    sa.Column('world_consequences', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('plot_thread_key', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key', name='uq_quest_world_key')
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quests_world_id'), ['world_id'], unique=False)

    op.create_table('relationship_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('character_a_id', sa.String(length=36), nullable=False),
    sa.Column('character_b_id', sa.String(length=36), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('before', sa.Integer(), nullable=False),
    sa.Column('after', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('clamped', sa.Boolean(), nullable=False),
    sa.Column('world_minute', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationship_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationship_changes_character_a_id'), ['character_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_changes_character_b_id'), ['character_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationship_changes_world_id'), ['world_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('character_a_id', sa.String(length=36), nullable=False),
    sa.Column('character_b_id', sa.String(length=36), nullable=False),
    sa.Column('affection', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('respect', sa.Integer(), nullable=False),
    sa.Column('fear', sa.Integer(), nullable=False),
    sa.Column('hatred', sa.Integer(), nullable=False),
    sa.Column('suspicion', sa.Integer(), nullable=False),
    sa.Column('dependency', sa.Integer(), nullable=False),
    sa.Column('familiarity', sa.Integer(), nullable=False),
    sa.Column('last_interaction_minute', sa.BigInteger(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_a_id', 'character_b_id', name='uq_relationship_pair')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_character_a_id'), ['character_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_character_b_id'), ['character_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_world_id'), ['world_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('required_realm', sa.String(length=60), nullable=False),
    sa.Column('required_stage', sa.String(length=60), nullable=False),
    sa.Column('spiritual_cost', sa.Integer(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effects', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key', name='uq_skill_world_key')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_world_id'), ['world_id'], unique=False)

    op.create_table('turn_traces',
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('turn_id')
    )
    with op.batch_alter_table('turn_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turn_traces_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turn_traces_world_id'), ['world_id'], unique=False)

    op.create_table('turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('player_input', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('world_minute_before', sa.BigInteger(), nullable=False),
    sa.Column('world_minute_after', sa.BigInteger(), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'turn_number', name='uq_turn_session_number')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index('idx_turns_idem', ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_turns_session_id'), ['session_id'], unique=False)

    op.create_table('worlds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_minute', sa.BigInteger(), nullable=False),
    sa.Column('calendar_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('world_seed', sa.String(length=120), nullable=False),
    sa.Column('content_pack', sa.String(length=120), nullable=False),
    sa.Column('rule_version', sa.String(length=40), nullable=False),
    sa.Column('narrative_tension', sa.Float(), nullable=False),
    sa.Column('tension_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('world_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('character_type', sa.String(length=40), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=40), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('location_key', sa.String(length=120), nullable=True),
    sa.Column('faction_key', sa.String(length=120), nullable=True),
    sa.Column('faction_rank', sa.String(length=120), nullable=True),
    sa.Column('realm', sa.String(length=60), nullable=False),
    sa.Column('realm_stage', sa.String(length=60), nullable=False),
    sa.Column('cultivation_progress', sa.Float(), nullable=False),
    sa.Column('cultivation_speed', sa.Float(), nullable=False),
    sa.Column('spiritual_root', sa.String(length=60), nullable=False),
    sa.Column('bottleneck', sa.Float(), nullable=False),
    sa.Column('mental_state', sa.Float(), nullable=False),
    sa.Column('foundation_quality', sa.Float(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('max_health', sa.Integer(), nullable=False),
    sa.Column('spiritual_power', sa.Integer(), nullable=False),
    sa.Column('max_spiritual_power', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('perception', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('willpower', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('personality', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('long_term_goal', sa.Text(), nullable=False),
    sa.Column('short_term_goals', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('current_emotion', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('injuries', sa.Float(), nullable=False),
    sa.Column('schedule', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('reputation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('death_event_id', sa.String(length=36), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('character_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key', name='uq_character_world_key')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index('idx_characters_world_location', ['world_id', 'location_id', 'alive'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_alive'), ['alive'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_character_type'), ['character_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_world_id'), ['world_id'], unique=False)

    op.create_table('factions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('faction_type', sa.String(length=60), nullable=False),
    sa.Column('headquarters_key', sa.String(length=120), nullable=True),
    sa.Column('resources', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('territory', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('military_power', sa.Float(), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.Column('leader_key', sa.String(length=120), nullable=True),
    sa.Column('alliances', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('enemies', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('goals', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('internal_conflicts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('faction_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key', name='uq_faction_world_key')
    )
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factions_world_id'), ['world_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('coordinates', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('danger_level', sa.Integer(), nullable=False),
    sa.Column('spirit_density', sa.Float(), nullable=False),
    sa.Column('faction_key', sa.String(length=120), nullable=True),
    sa.Column('accessible', sa.Boolean(), nullable=False),
    sa.Column('travel_minutes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('location_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key', name='uq_location_world_key')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('idx_locations_parent', ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_world_id'), ['world_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_world_id'))
        batch_op.drop_index('idx_locations_parent')

    op.drop_table('locations')
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factions_world_id'))

    op.drop_table('factions')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_world_id'))
        batch_op.drop_index(batch_op.f('ix_characters_character_type'))
        batch_op.drop_index(batch_op.f('ix_characters_alive'))
        batch_op.drop_index('idx_characters_world_location')

    op.drop_table('characters')
    op.drop_table('worlds')
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_session_id'))
        batch_op.drop_index('idx_turns_idem')

    op.drop_table('turns')
    with op.batch_alter_table('turn_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turn_traces_world_id'))
        batch_op.drop_index(batch_op.f('ix_turn_traces_session_id'))

    op.drop_table('turn_traces')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_world_id'))

    op.drop_table('skills')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_world_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_character_b_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_character_a_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('relationship_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationship_changes_world_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_changes_character_b_id'))
        batch_op.drop_index(batch_op.f('ix_relationship_changes_character_a_id'))

    op.drop_table('relationship_changes')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_world_id'))
        batch_op.drop_index(batch_op.f('ix_quests_status'))

    op.drop_table('quests')
    with op.batch_alter_table('plot_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_threads_world_id'))
        batch_op.drop_index(batch_op.f('ix_plot_threads_status'))

    op.drop_table('plot_threads')
    with op.batch_alter_table('narrative_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_narrative_segments_session_id'))

    op.drop_table('narrative_segments')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_world_id'))
        batch_op.drop_index(batch_op.f('ix_memories_owner_character_id'))
        batch_op.drop_index(batch_op.f('ix_memories_memory_type'))
        batch_op.drop_index('idx_memories_owner_importance')

    op.drop_table('memories')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_world_id'))

    op.drop_table('items')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_item_key'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_character_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_sessions_world_id'))
        batch_op.drop_index(batch_op.f('ix_game_sessions_player_character_id'))

    op.drop_table('game_sessions')
    with op.batch_alter_table('facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facts_world_id'))

    op.drop_table('facts')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_world_minute'))
        batch_op.drop_index(batch_op.f('ix_events_world_id'))
        batch_op.drop_index(batch_op.f('ix_events_turn_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index('idx_events_world_minute')
        batch_op.drop_index('idx_events_actor')

    op.drop_table('events')
    with op.batch_alter_table('character_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_skills_skill_key'))
        batch_op.drop_index(batch_op.f('ix_character_skills_character_id'))

    op.drop_table('character_skills')
    with op.batch_alter_table('character_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_knowledge_knowledge_state'))
        batch_op.drop_index(batch_op.f('ix_character_knowledge_fact_id'))
        batch_op.drop_index(batch_op.f('ix_character_knowledge_character_id'))

    op.drop_table('character_knowledge')
    # ### end Alembic commands ###
